import XCTest

@testable import SupremeSampler

/// Specifies reading a saved `.psc` script back into rules: the rules,
/// sample size and folder balance come back from the script's own SQL,
/// and anything the app wouldn't have written -- a hand edit -- is
/// reported rather than silently kept or dropped.
final class ScriptReaderTests: XCTestCase {
    private let generatedAt = Date(timeIntervalSince1970: 1_790_000_000)

    private func script(
        _ filter: SampleFilter, size: Int = 250, balance: FolderBalance = .off
    ) -> String {
        RandomSampleScriptGenerator.generate(
            sampleSize: size, filter: filter, folderBalance: balance, generatedAt: generatedAt)
    }

    private func read(_ text: String, file: StaticString = #filePath, line: UInt = #line) throws -> ReadScript {
        guard case .read(let result) = ScriptReader.read(text) else {
            XCTFail("expected a readable script, got \(ScriptReader.read(text))", file: file, line: line)
            throw XCTSkip("unreadable")
        }
        return result
    }

    private func flat(_ rules: FilterRule...) -> SampleFilter {
        SampleFilter(root: RuleGroup(match: .all, rules: rules))
    }

    // MARK: - Scripts as the app wrote them

    func test_givenAGeneratedScript_whenRead_thenItsRulesSizeAndBalanceComeBackUnchanged() throws {
        let filter = flat(.rating(.atLeast(3)), .pendingDeletion(false), .bookmark(BookmarkFilter(values: [5], mode: .none)))

        let result = try read(script(filter, size: 1234, balance: .balanced))

        XCTAssertEqual(result.filter, filter)
        XCTAssertEqual(result.sampleSize, 1234)
        XCTAssertEqual(result.folderBalance, .balanced)
        XCTAssertTrue(result.isExactlyAsGenerated)
        XCTAssertEqual(result.unreadableClauses, [])
    }

    func test_givenEachFolderBalance_whenRead_thenTheBalanceComesBack() throws {
        for balance in FolderBalance.allCases {
            let result = try read(script(flat(.rating(.exactly(2))), balance: balance))
            XCTAssertEqual(result.folderBalance, balance)
            XCTAssertTrue(result.isExactlyAsGenerated, "\(balance)")
        }
    }

    func test_givenAnUnfilteredScript_whenRead_thenItMatchesTheWholeCatalog() throws {
        let result = try read(script(SampleFilter()))

        XCTAssertTrue(result.filter.isUnconstrained)
        XCTAssertTrue(result.isExactlyAsGenerated)
    }

    func test_givenRandomRuleTrees_whenGeneratedThenRead_thenEachScriptReadsBackExactly() throws {
        // The property that makes reading trustworthy: whatever the
        // generator writes, reading it gives rules that generate the same
        // file again -- so the file means exactly those rules.
        var rng = RandomRuleTrees.SeededGenerator(state: 20_260_927)
        for trial in 0..<500 {
            let filter = SampleFilter(root: RandomRuleTrees.randomGroup(depth: 3, using: &rng))
            let balance = FolderBalance.allCases.randomElement(using: &rng)!
            let text = script(filter, size: trial + 1, balance: balance)

            let result = try read(text)

            XCTAssertEqual(result.unreadableClauses, [], "trial \(trial): \(filter)")
            XCTAssertTrue(result.isExactlyAsGenerated, "trial \(trial): \(filter)\n\(result.fileOnlyLines)")
            XCTAssertEqual(
                SQLPredicateText.render(result.filter), SQLPredicateText.render(filter), "trial \(trial)")
            XCTAssertEqual(result.sampleSize, trial + 1)
            XCTAssertEqual(result.folderBalance, balance)
        }
    }

    func test_givenTextNeedingEscapes_whenRead_thenTheExactTextComesBack() throws {
        let filter = flat(
            .label(LabelFilter(labels: ["", "O'Brien", "選択", "a, b", "{x}"], mode: .any)),
            .path(PathFilter(kind: .contains, text: "100%_x\\y'z", negated: true)),
            .keywordPath(KeywordPathFilter(kind: .hasPart, text: "Été\\Oak", negated: false)),
            .fileType(FileTypeFilter(extensions: ["", "lr_", "jpg"], mode: .none)))

        let result = try read(script(filter))

        XCTAssertEqual(result.filter, filter)
    }

    func test_givenCRLFLineEndings_whenRead_thenItStillCountsAsGenerated() throws {
        // Script Studio re-saves files with CRLF; that's not a hand edit.
        let text = script(flat(.rating(.atLeast(4)))).replacingOccurrences(of: "\n", with: "\r\n")

        let result = try read(text)

        XCTAssertTrue(result.isExactlyAsGenerated)
    }

    func test_givenAnOlderAppName_whenRead_thenItStillCountsAsGenerated() throws {
        // Releases up to v0.2.0 signed scripts "SupremeSampler".
        let text = script(flat(.rating(.atLeast(4)))).replacingOccurrences(
            of: "Generated by \(AppName.current) on", with: "Generated by SupremeSampler on")

        XCTAssertTrue(try read(text).isExactlyAsGenerated)
    }

    // MARK: - Hand edits

    func test_givenAnEditedBoilerplateLine_whenRead_thenTheRulesComeBackAndTheLineIsReported() throws {
        let filter = flat(.rating(.atLeast(3)))
        let text = script(filter).replacingOccurrences(
            of: "  ROWID_OVERSAMPLE_MARGIN = 1.15;", with: "  ROWID_OVERSAMPLE_MARGIN = 1.5;")

        let result = try read(text)

        XCTAssertEqual(result.filter, filter)
        XCTAssertFalse(result.isExactlyAsGenerated)
        XCTAssertEqual(result.fileOnlyLines.map(\.text), ["  ROWID_OVERSAMPLE_MARGIN = 1.5;"])
        XCTAssertEqual(result.generatedOnlyLines, ["  ROWID_OVERSAMPLE_MARGIN = 1.15;"])
    }

    func test_givenTheSamplingQueryEditedButNotTheCountQuery_whenRead_thenTheEditIsReported() throws {
        // The rules are read from the count query; the two must agree.
        let text = script(flat(.rating(.atLeast(3)))).replacingOccurrences(
            of: "+ ') AND Rating >= 3'", with: "+ ') AND Rating >= 4'")

        let result = try read(text)

        XCTAssertEqual(result.filter, flat(.rating(.atLeast(3))))
        XCTAssertFalse(result.isExactlyAsGenerated)
    }

    func test_givenAHandWrittenCondition_whenRead_thenTheOtherRulesAreRecoveredAndItIsReported() throws {
        let filter = flat(.rating(.atLeast(3)), .pendingDeletion(false))
        let text = script(filter).replacingOccurrences(of: "Rating >= 3", with: "Rating > 3")

        let result = try read(text)

        XCTAssertEqual(result.filter, flat(.pendingDeletion(false)))
        XCTAssertEqual(result.unreadableClauses, ["Rating > 3"])
        XCTAssertFalse(result.isExactlyAsGenerated)
    }

    func test_givenAnUnreadableConditionInANestedGroup_whenRead_thenOnlyThatConditionIsDropped() throws {
        let filter = flat(
            .group(RuleGroup(match: .any, rules: [.rating(.exactly(5)), .rating(.exactly(1))])),
            .pendingDeletion(false))
        let text = script(filter).replacingOccurrences(of: "Rating = 1", with: "Rating = 1 + 0")

        let result = try read(text)

        XCTAssertEqual(
            result.filter,
            flat(.group(RuleGroup(match: .any, rules: [.rating(.exactly(5))])), .pendingDeletion(false)))
        XCTAssertEqual(result.unreadableClauses, ["Rating = 1 + 0"])
    }

    func test_givenAKeywordListInAnotherOrder_whenRead_thenTheKeywordsAreKeptAndTheEditReported() throws {
        let filter = flat(.category(CategoryFilter(propGUIDs: ["AAA", "BBB"], mode: .any)))
        // Quotes are doubled inside the script's Pascal string literal.
        let text = script(filter).replacingOccurrences(of: "''AAA'', ''BBB''", with: "''BBB'', ''AAA''")
        XCTAssertNotEqual(text, script(filter))

        let result = try read(text)

        XCTAssertEqual(result.unreadableClauses, [])
        XCTAssertEqual(
            SQLPredicateText.render(result.filter), SQLPredicateText.render(filter), "the same keywords")
        XCTAssertFalse(result.isExactlyAsGenerated)
    }

    // MARK: - Lines the comparison skips can't hide code

    func test_givenCodeAfterABraceInARuleSummaryLine_whenRead_thenTheLineIsReported() throws {
        // "}" ends the header comment, so the rest of the line would run.
        let injected = "  Rating filter: } begin ShowMessage('x'); end. { y"
        let text = script(flat(.rating(.atLeast(3)))).replacingOccurrences(
            of: "  Rating filter: at least 3", with: "  Rating filter: at least 3\n" + injected)

        let result = try read(text)

        XCTAssertFalse(result.isExactlyAsGenerated)
        XCTAssertEqual(result.fileOnlyLines.map(\.text), [injected])
    }

    func test_givenCodeHiddenInTheGeneratedByLine_whenRead_thenTheLineIsReported() throws {
        let original = script(flat(.rating(.atLeast(3))))
        let generatedBy = try XCTUnwrap(original.components(separatedBy: "\n").first { $0.hasPrefix("  Generated by") })
        let injected = "  Generated by } begin ShowMessage('x'); end. { on ."

        let result = try read(original.replacingOccurrences(of: generatedBy, with: injected))

        XCTAssertFalse(result.isExactlyAsGenerated)
        XCTAssertTrue(result.fileOnlyLines.map(\.text).contains(injected))
    }

    func test_givenASecondFormatStampWithCode_whenRead_thenItIsRefused() {
        let stamp = ScriptFormats.stamp(version: 1)
        let text = script(flat(.rating(.atLeast(3)))).replacingOccurrences(
            of: stamp, with: stamp + "\n" + stamp + " } begin ShowMessage('x'); end. {")

        guard case .notAScript = ScriptReader.read(text) else { return XCTFail("one stamp per script") }
    }

    // MARK: - Hostile input

    func test_givenParenthesesNestedFarDeeperThanTheAppWrites_whenRead_thenItIsRefusedQuickly() {
        // Reading recurses per level: thousands of levels once took
        // seconds, and 8,000 overflowed the stack.
        let depth = 10_000
        let deep = String(repeating: "(", count: depth) + "Rating = 1" + String(repeating: ")", count: depth)
        let text = script(flat(.rating(.exactly(1)))).replacingOccurrences(of: "Rating = 1", with: deep)
        let start = Date()

        let reading = ScriptReader.read(text)

        XCTAssertLessThan(Date().timeIntervalSince(start), 1)
        guard case .notAScript(let reason) = reading else { return XCTFail("refused") }
        XCTAssertTrue(reason.contains("nest"), reason)
    }

    func test_givenTheDeepestNestingTheRuleBuilderMakesInPractice_whenRead_thenItReadsExactly() throws {
        var group = RuleGroup(match: .any, rules: [.rating(.exactly(5)), .keywordCount(.atLeast(2))])
        for level in 0..<12 {
            group = RuleGroup(match: [GroupMatch.all, .any, .none][level % 3], rules: [.group(group), .pendingDeletion(false)])
        }

        XCTAssertTrue(try read(script(SampleFilter(root: group))).isExactlyAsGenerated)
    }

    // MARK: - Not a script this app can read

    func test_givenTextThatIsNotAScript_whenRead_thenItSaysSo() {
        guard case .notAScript = ScriptReader.read("hello, world\n") else {
            return XCTFail("plain text isn't a sampling script")
        }
    }

    func test_givenAScriptWithNoSampleSize_whenRead_thenItSaysSo() {
        let text = script(flat(.rating(.atLeast(3)))).replacingOccurrences(of: "  SAMPLE_SIZE = 250;", with: "")
        guard case .notAScript = ScriptReader.read(text) else {
            return XCTFail("a sampling script declares SAMPLE_SIZE")
        }
    }

    func test_givenTheHandWrittenReferenceScript_whenRead_thenItReadsAsUnfilteredWithItsOwnHeaderReported() throws {
        // The script this app generalizes: same body, its own header.
        let reference = try XCTUnwrap(ReferenceScript.load())

        let result = try read(reference.text)

        XCTAssertTrue(result.filter.isUnconstrained)
        XCTAssertEqual(result.sampleSize, reference.sampleSize)
        XCTAssertFalse(result.isExactlyAsGenerated)
        let firstBodyLine = try XCTUnwrap(reference.text.components(separatedBy: "\n").firstIndex(of: "const"))
        XCTAssertTrue(
            result.fileOnlyLines.allSatisfy { $0.number <= firstBodyLine },
            "only the header differs: \(result.fileOnlyLines)")
    }
}

/// Specifies script format versions: every script names the format it
/// follows, an unedited script in an older format reads cleanly (and is
/// upgraded by saving it), and a newer or unknown format isn't guessed at.
final class ScriptFormatTests: XCTestCase {
    private let filter = SampleFilter(root: RuleGroup(match: .all, rules: [.rating(.atLeast(3))]))

    private func current(_ filter: SampleFilter) -> String {
        RandomSampleScriptGenerator.generate(sampleSize: 50, filter: filter)
    }

    /// Stands in for a format from before a (made-up) change to the
    /// boilerplate: format 1 used a different oversample margin.
    private struct OldFormat: ScriptFormat {
        let version = 1
        func generate(sampleSize: Int, filter: SampleFilter, folderBalance: FolderBalance) -> String {
            RandomSampleScriptGenerator.generate(sampleSize: sampleSize, filter: filter, folderBalance: folderBalance)
                .replacingOccurrences(of: "ROWID_OVERSAMPLE_MARGIN = 1.15;", with: "ROWID_OVERSAMPLE_MARGIN = 1.10;")
        }
    }

    /// The format after that change: today's output, stamped 2.
    private struct NewFormat: ScriptFormat {
        let version = 2
        func generate(sampleSize: Int, filter: SampleFilter, folderBalance: FolderBalance) -> String {
            RandomSampleScriptGenerator.generate(sampleSize: sampleSize, filter: filter, folderBalance: folderBalance)
                .replacingOccurrences(of: ScriptFormats.stamp(version: 1), with: ScriptFormats.stamp(version: 2))
        }
    }

    private let versions: [any ScriptFormat] = [OldFormat(), NewFormat()]

    func test_givenAGeneratedScript_thenItsHeaderNamesTheLatestFormat() {
        XCTAssertEqual(RandomSampleScriptGenerator.formatVersion, ScriptFormats.latest.version)
        XCTAssertTrue(current(filter).contains("\n" + ScriptFormats.stamp(version: ScriptFormats.latest.version) + "\n"))
    }

    func test_givenAScriptSavedBeforeFormatsWereStamped_whenRead_thenItIsFormatOneAsGenerated() throws {
        let unstamped = current(filter).replacingOccurrences(of: ScriptFormats.stamp(version: 1) + "\n", with: "")
        guard case .read(let result) = ScriptReader.read(unstamped) else { return XCTFail("readable") }

        XCTAssertEqual(result.formatVersion, 1)
        XCTAssertTrue(result.isExactlyAsGenerated)
        XCTAssertEqual(result.filter, filter)
    }

    func test_givenAnUneditedOlderFormatScript_whenRead_thenItReadsCleanlyAndIsMarkedForUpgrade() throws {
        let old = OldFormat().generate(sampleSize: 50, filter: filter, folderBalance: .off)
        guard case .read(let result) = ScriptReader.read(old, formats: versions) else { return XCTFail("readable") }

        XCTAssertEqual(result.formatVersion, 1)
        XCTAssertTrue(result.isOlderFormat)
        XCTAssertTrue(result.isExactlyAsGenerated, "compared with its own format: \(result.fileOnlyLines)")
        XCTAssertEqual(result.filter, filter)
    }

    func test_givenAnEditedOlderFormatScript_whenRead_thenOnlyTheEditIsReported() throws {
        let old = OldFormat().generate(sampleSize: 50, filter: filter, folderBalance: .off)
            .replacingOccurrences(of: "ROWID_MAX_SAMPLE_ATTEMPTS = 8;", with: "ROWID_MAX_SAMPLE_ATTEMPTS = 9;")
        guard case .read(let result) = ScriptReader.read(old, formats: versions) else { return XCTFail("readable") }

        XCTAssertEqual(result.fileOnlyLines.map(\.text), ["  ROWID_MAX_SAMPLE_ATTEMPTS = 9;"])
    }

    func test_givenTheLatestFormat_whenRead_thenItIsNotMarkedForUpgrade() throws {
        let new = NewFormat().generate(sampleSize: 50, filter: filter, folderBalance: .off)
        guard case .read(let result) = ScriptReader.read(new, formats: versions) else { return XCTFail("readable") }

        XCTAssertEqual(result.formatVersion, 2)
        XCTAssertFalse(result.isOlderFormat)
        XCTAssertTrue(result.isExactlyAsGenerated)
    }

    func test_givenAFormatNewerThanTheApp_whenRead_thenItIsRefusedRatherThanGuessed() {
        let future = current(filter).replacingOccurrences(
            of: ScriptFormats.stamp(version: 1), with: ScriptFormats.stamp(version: 99))
        guard case .notAScript(let reason) = ScriptReader.read(future) else { return XCTFail("refused") }
        XCTAssertTrue(reason.contains("newer version"), reason)
    }

    func test_givenAStampLikeLineOutsideTheHeader_whenRead_thenItDoesNotNameTheFormat() throws {
        // Only the header comment names the format; the same text further
        // down is an ordinary (edited) line.
        let text = current(filter).replacingOccurrences(
            of: "const\n  SAMPLE_SIZE", with: ScriptFormats.stamp(version: 99) + "\nconst\n  SAMPLE_SIZE")
        guard case .read(let result) = ScriptReader.read(text) else { return XCTFail("readable") }

        XCTAssertEqual(result.formatVersion, 1)
        XCTAssertEqual(result.fileOnlyLines.map(\.text), [ScriptFormats.stamp(version: 99)])
    }

    func test_givenAGarbledFormatStamp_whenRead_thenItIsRefused() {
        let garbled = current(filter).replacingOccurrences(
            of: ScriptFormats.stamp(version: 1), with: ScriptFormats.stampPrefix + "one")
        guard case .notAScript = ScriptReader.read(garbled) else { return XCTFail("refused") }
    }
}
