{
  Random Catalog Sample
  =====================

  Returns a fresh random sample of catalog items in a new Photo Supreme tab.

  Generated by Supreme Sampler on 2026-09-27T12:00:00Z.
}

const
  SAMPLE_SIZE = 10000;

// Extra margin above the expected hit count when oversampling random
// rowids. Benchmarked safe at 2.4x oversample against the real catalog.
const
  ROWID_OVERSAMPLE_MARGIN = 1.15;

// Safety cap on retry passes, in case a shortfall never closes.
const
  ROWID_MAX_SAMPLE_ATTEMPTS = 8;

// Hard ceiling on random rowids drawn per pass, in case catalog
// density ever drops low enough to make a batch huge.
const
  ROWID_MAX_BATCH_SIZE = 100000;

function RandomItemGUIDs(ACount: Integer): TStringList;
var
  AExtentSet: TDBXOMClientDataSet;
  ASampleSet: TDBXOMClientDataSet;
  ACandidates: TStringList;
  ATotalRows, AMaxRowID: Integer;
  ADensity: Double;
  ABatchSize, AAttempt, AShortfall, I: Integer;
begin
  Randomize;
  result := TStringList.Create;
  result.Sorted := True;
  result.Duplicates := dupIgnore;

  AExtentSet := PublicCatalog.NewDataSet;
  try
    AExtentSet.CommandText :=
      'SELECT COUNT(*) AS RowCount, MAX(rowid) AS MaxRowID FROM idCatalogItem';
    AExtentSet.OpenSet;
    ATotalRows := AExtentSet.FieldValue('RowCount');
    AMaxRowID := AExtentSet.FieldValue('MaxRowID');
    AExtentSet.CloseSet;
  finally
    PublicCatalog.FreeDataSet(AExtentSet);
  end;

  if (ATotalRows > 0) and (AMaxRowID > 0) then
  begin
    if ACount > ATotalRows then
      ACount := ATotalRows;

    ADensity := ATotalRows / AMaxRowID;

    AAttempt := 0;
    while (result.Count < ACount) and (AAttempt < ROWID_MAX_SAMPLE_ATTEMPTS) do
    begin
      Inc(AAttempt);
      AShortfall := ACount - result.Count;
      ABatchSize := Trunc(AShortfall / ADensity * ROWID_OVERSAMPLE_MARGIN) + 1;
      if ABatchSize > ROWID_MAX_BATCH_SIZE then
        ABatchSize := ROWID_MAX_BATCH_SIZE;

      ACandidates := TStringList.Create;
      try
        for I := 1 to ABatchSize do
          ACandidates.Add(IntToStr(Trunc(Random * AMaxRowID) + 1));

        ASampleSet := PublicCatalog.NewDataSet;
        try
          ASampleSet.CommandText :=
            'SELECT GUID FROM idCatalogItem WHERE rowid IN (' +
            ACandidates.CommaText + ')';
          ASampleSet.OpenSet;
          while (not ASampleSet.EndOfSet) and (result.Count < ACount) do
          begin
            result.Add(ASampleSet.FieldValue('GUID'));
            ASampleSet.NextInSet;
          end;
          ASampleSet.CloseSet;
        finally
          PublicCatalog.FreeDataSet(ASampleSet);
        end;
      finally
        ACandidates.Free;
      end;
    end;
  end;
end;


// Materializes the random GUIDs into full catalog items (with datasets).
function BuildRandomItems: TCatalogItems;
var
  AGUIDs: TStringList;
  AClassGUID: String;
begin
  result := TCatalogItems.Create(TCatalogItem, '');

  AGUIDs := RandomItemGUIDs(SAMPLE_SIZE);
  try
    AClassGUID := PublicCatalog.StoreItemGUIDsToTempList(AGUIDs, False);
    try
      PublicCatalog.EnumItemsFromTempListGUID(AClassGUID, result);
    finally
      PublicCatalog.RemoveItemsFromTempListForClassGUID(AClassGUID);
    end;
  finally
    AGUIDs.Free;
  end;
end;


procedure OpenNewTabForDataset(ADatasets: TDBXOMDataSets);
var
  AData: TidElement;
  AColl: Variant;
begin
  AData := TidElement.Create(nil);
  try
    PublicBroadCast(nil, 'OpenNewTab', nil);
    PublicBroadCastRequest(nil, 'ActiveCollection', AData);
    AColl := AData.Data;
    AColl.Clear;
    AColl.Items._DataSets := ADatasets;
    PublicBroadCast(nil, 'RefreshActiveCollection', nil);
  finally
    AData.Free;
  end;
end;


procedure OpenRandomSample;
var
  AItems: TCatalogItems;
  ADatasets: TDBXOMDataSets;
begin
  AItems := BuildRandomItems;
  try
    ADatasets := AItems.DataSets;
    AItems._DataSets := TDBXOMDataSets.Create(TDBXOMDataSet, '');
  finally
    AItems.Free;
  end;

  OpenNewTabForDataset(ADatasets);
end;


begin
  OpenRandomSample;
end;
