import Foundation

/// What reading a script file found.
///
/// An `enum` whose cases carry values -- a Rust `enum` with data, or a
/// TS discriminated union.
enum ScriptReading: Equatable {
    /// Not a sampling script this app can read: `reason` says what's missing.
    case notAScript(reason: String)
    case read(ReadScript)
}

/// A sampling script read back into the settings that generate it.
struct ReadScript: Equatable {
    /// One line of the file, numbered from 1.
    struct Line: Equatable {
        let number: Int
        let text: String
    }

    var sampleSize: Int
    var folderBalance: FolderBalance
    /// The rules, less any `unreadableClauses`.
    var filter: SampleFilter
    /// Conditions in the script's SQL that weren't recognized and are
    /// left out of `filter` -- usually hand edits.
    var unreadableClauses: [String]
    /// Lines of the file that the app wouldn't write for these settings:
    /// what saving over the file would drop.
    var fileOnlyLines: [Line]
    /// Lines the app would write that the file doesn't have.
    var generatedOnlyLines: [String]
    /// The `ScriptFormat` version the file was written in.
    var formatVersion: Int
    /// Written in an older format than the newest one the app knows:
    /// saving it again upgrades it.
    var isOlderFormat: Bool

    /// True when the file is exactly what its format writes for these
    /// settings, so nothing in it would be lost by saving it again.
    var isExactlyAsGenerated: Bool {
        unreadableClauses.isEmpty && fileOnlyLines.isEmpty && generatedOnlyLines.isEmpty
    }
}

/// Reads a `.psc` file written by this app back into its rules, sample
/// size and folder balance -- the other half of saving. Pure: text in,
/// `ScriptReading` out; the caller reads the file.
///
/// The header's `Script format: N` stamp (none means 1) picks the
/// `ScriptFormat` the file follows; that format reads the settings (the
/// rules from the count query's SQL, via `SQLPredicateReader`). Then the
/// same format generates the script again from what was read, and it's
/// compared with the file line by line. That is what makes the reading
/// trustworthy: if the two are identical, the file means exactly these
/// settings. Any difference is a hand edit, reported rather than guessed
/// at. Comparing against the file's own format, not the latest, is what
/// tells an older script (upgraded by saving it) from an edited one.
///
/// Some differences aren't edits and are ignored: CRLF line endings
/// (Script Studio re-saves files that way), the "Generated by" line,
/// whose app name and time vary between saves, the format stamp itself
/// (older scripts have none), and the header's rule summary. The summary
/// is only a description, rewritten from the rules on every save, and
/// rules that mean the same thing can describe themselves differently
/// (every rule that matches everything renders `1 = 1`, whatever it
/// was), so comparing it would report edits nobody made.
enum ScriptReader {
    /// `formats` is every format the app knows, oldest first; tests pass
    /// their own.
    static func read(_ text: String, formats: [any ScriptFormat] = ScriptFormats.all) -> ScriptReading {
        let lines = normalizedLines(text)

        guard let version = ScriptFormats.version(of: lines) else {
            return .notAScript(reason: "Its script format line isn't one Supreme Sampler writes.")
        }
        guard let format = formats.first(where: { $0.version == version }) else {
            if let newest = formats.last, version > newest.version {
                return .notAScript(
                    reason: "It was written by a newer version of Supreme Sampler (script format \(version)).")
            }
            return .notAScript(reason: "Its script format (\(version)) isn't one Supreme Sampler knows.")
        }
        let settings: ScriptSettings
        switch format.settings(in: lines) {
        case .failure(let error): return .notAScript(reason: error.reason)
        case .success(let read): settings = read
        }

        let regenerated = normalizedLines(
            format.generate(
                sampleSize: settings.sampleSize, filter: settings.filter, folderBalance: settings.folderBalance))

        // `difference(from:)` is the standard library's line diff (a
        // Myers diff, like `diff`/`git diff` use): insertions are what the
        // file has that the regenerated script doesn't, removals the reverse.
        let fileLines = comparableLines(lines)
        let generatedLines = comparableLines(regenerated)
        let difference = fileLines.map(\.key).difference(from: generatedLines.map(\.key))
        var fileOnly: [ReadScript.Line] = []
        var generatedOnly: [String] = []
        for change in difference {
            switch change {
            case .insert(let offset, _, _): fileOnly.append(fileLines[offset].line)
            case .remove(let offset, _, _): generatedOnly.append(generatedLines[offset].line.text)
            }
        }

        return .read(
            ReadScript(
                sampleSize: settings.sampleSize, folderBalance: settings.folderBalance, filter: settings.filter,
                unreadableClauses: settings.unreadableClauses,
                fileOnlyLines: fileOnly.sorted { $0.number < $1.number }, generatedOnlyLines: generatedOnly,
                formatVersion: version, isOlderFormat: version < (formats.last?.version ?? version)))
    }

    /// LF line endings, no byte-order mark, no trailing blank lines (a
    /// missing final newline isn't an edit worth reporting).
    private static func normalizedLines(_ text: String) -> [String] {
        var body = text.replacingOccurrences(of: "\r\n", with: "\n")
        if body.hasPrefix("\u{FEFF}") { body.removeFirst() }
        var lines = body.components(separatedBy: "\n")
        while lines.last?.trimmingCharacters(in: .whitespaces).isEmpty == true { lines.removeLast() }
        return lines
    }

    private static let generatedByPrefix = "  Generated by "

    /// A line to compare (`key`), and the line itself for reporting.
    private struct ComparableLine {
        let key: String
        let line: ReadScript.Line
    }

    /// `lines` less the header's rule summary and format stamp, with the
    /// "Generated by" line made the same for every app name and time.
    private static func comparableLines(_ lines: [String]) -> [ComparableLine] {
        let headerEnd = lines.firstIndex(of: "}") ?? 0
        return lines.enumerated().compactMap { index, text in
            if index < headerEnd && (isRuleSummary(text) || text.hasPrefix(ScriptFormats.stampPrefix)) { return nil }
            let isGeneratedBy = text.hasPrefix(generatedByPrefix) && text.contains(" on ") && text.hasSuffix(".")
            return ComparableLine(
                key: isGeneratedBy ? generatedByPrefix : text, line: ReadScript.Line(number: index + 1, text: text))
        }
    }

    /// The labels `RandomSampleScriptGenerator` starts rule summary lines with.
    private static let ruleSummaryLabels = [
        "Rating filter:", "Category filter:", "Path filter:", "Keyword path filter:", "Keyword count filter:",
        "Label filter:", "File type filter:", "Bookmark filter:", "Pending deletion:",
        "Match all of:", "Match any of:", "Match none of:",
    ]

    private static func isRuleSummary(_ line: String) -> Bool {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        return ruleSummaryLabels.contains { trimmed.hasPrefix($0) }
    }
}
