import Foundation

/// What reading a script file found.
///
/// An `enum` whose cases carry values -- a Rust `enum` with data, or a
/// TS discriminated union.
enum ScriptReading: Equatable {
    /// Not a sampling script this app can read: `reason` says what's missing.
    case notAScript(reason: String)
    case read(ReadScript)
}

/// A sampling script read back into the settings that generate it.
struct ReadScript: Equatable {
    /// One line of the file, numbered from 1.
    struct Line: Equatable {
        let number: Int
        let text: String
    }

    var sampleSize: Int
    var folderBalance: FolderBalance
    /// The rules, less any `unreadableClauses`.
    var filter: SampleFilter
    /// Conditions in the script's SQL that weren't recognized and are
    /// left out of `filter` -- usually hand edits.
    var unreadableClauses: [String]
    /// Lines of the file that the app wouldn't write for these settings:
    /// what saving over the file would drop.
    var fileOnlyLines: [Line]
    /// Lines the app would write that the file doesn't have.
    var generatedOnlyLines: [String]
    /// The `ScriptFormat` version the file was written in.
    var formatVersion: Int
    /// Written in an older format than the newest one the app knows:
    /// saving it again upgrades it.
    var isOlderFormat: Bool

    /// True when the file is exactly what its format writes for these
    /// settings, so nothing in it would be lost by saving it again.
    var isExactlyAsGenerated: Bool {
        unreadableClauses.isEmpty && fileOnlyLines.isEmpty && generatedOnlyLines.isEmpty
    }
}

/// Reads a `.psc` file written by this app back into its rules, sample
/// size and folder balance -- the other half of saving. Pure: text in,
/// `ScriptReading` out; the caller reads the file.
///
/// The header's `Script format: N` stamp (none means 1) picks the
/// `ScriptFormat` the file follows; that format reads the settings (the
/// rules from the count query's SQL, via `SQLPredicateReader`). Then the
/// same format generates the script again from what was read, and it's
/// compared with the file line by line. That is what makes the reading
/// trustworthy: if the two are identical, the file means exactly these
/// settings. Any difference is a hand edit, reported rather than guessed
/// at. Comparing against the file's own format, not the latest, is what
/// tells an older script (upgraded by saving it) from an edited one.
///
/// Some differences aren't edits and are ignored: CRLF line endings
/// (Script Studio re-saves files that way), the "Generated by" line,
/// whose app name and time vary between saves, the format stamp itself
/// (older scripts have none), and the header's rule summary. The summary
/// is only a description, rewritten from the rules on every save, and
/// rules that mean the same thing can describe themselves differently
/// (every rule that matches everything renders `1 = 1`, whatever it
/// was), so comparing it would report edits nobody made.
enum ScriptReader {
    /// `formats` is every format the app knows, oldest first; tests pass
    /// their own.
    static func read(_ text: String, formats: [any ScriptFormat] = ScriptFormats.all) -> ScriptReading {
        let lines = normalizedLines(text)

        guard let version = ScriptFormats.version(of: lines) else {
            return .notAScript(reason: "Its script format line isn't one Supreme Sampler writes.")
        }
        guard let format = formats.first(where: { $0.version == version }) else {
            if let newest = formats.last, version > newest.version {
                return .notAScript(
                    reason: "It was written by a newer version of Supreme Sampler (script format \(version)).")
            }
            return .notAScript(reason: "Its script format (\(version)) isn't one Supreme Sampler knows.")
        }
        let settings: ScriptSettings
        switch format.settings(in: lines) {
        case .failure(let error): return .notAScript(reason: error.reason)
        case .success(let read): settings = read
        }

        let regenerated = normalizedLines(
            format.generate(
                sampleSize: settings.sampleSize, filter: settings.filter, folderBalance: settings.folderBalance))

        let (fileOnly, generatedOnly) = differences(comparableLines(lines), comparableLines(regenerated))

        return .read(
            ReadScript(
                sampleSize: settings.sampleSize, folderBalance: settings.folderBalance, filter: settings.filter,
                unreadableClauses: settings.unreadableClauses,
                fileOnlyLines: fileOnly, generatedOnlyLines: generatedOnly,
                formatVersion: version, isOlderFormat: version < (formats.last?.version ?? version)))
    }

    /// LF line endings, no byte-order mark, no trailing blank lines (a
    /// missing final newline isn't an edit worth reporting).
    private static func normalizedLines(_ text: String) -> [String] {
        var body = text.replacingOccurrences(of: "\r\n", with: "\n")
        if body.hasPrefix("\u{FEFF}") { body.removeFirst() }
        var lines = body.components(separatedBy: "\n")
        while lines.last?.trimmingCharacters(in: .whitespaces).isEmpty == true { lines.removeLast() }
        return lines
    }

    private static let generatedByPrefix = "  Generated by "

    /// A line to compare (`key`), and the line itself for reporting.
    ///
    /// The key is the line's UTF-8 bytes, not the `String`: Swift's `==`
    /// counts canonically equivalent text as equal (KELVIN SIGN is "K",
    /// GREEK QUESTION MARK is ";"), and SQLite and Pascal compare bytes.
    private struct ComparableLine {
        let key: [UInt8]
        let line: ReadScript.Line
    }

    /// `lines` less the header's rule summary and format stamp, with the
    /// "Generated by" line made the same for every app name and time.
    ///
    /// Only lines inside the header comment are ever skipped or masked,
    /// and only plain printable ASCII ones without a `}` -- which is all
    /// the generator writes there (`}` in header text becomes `)`, other
    /// characters `?`). A `}` ends the comment and the rest of the line
    /// would run as Pascal; checking bytes, not characters, keeps a `}`
    /// from hiding inside a character like U+0600 + `}`.
    private static func comparableLines(_ lines: [String]) -> [ComparableLine] {
        let header = ScriptFormats.headerRange(lines)
        return lines.enumerated().compactMap { index, text in
            let bytes = Array(text.utf8)
            let line = ReadScript.Line(number: index + 1, text: text)
            guard header.contains(index), isSkippableHeaderText(bytes) else { return ComparableLine(key: bytes, line: line) }
            if isRuleSummary(text) || text.hasPrefix(ScriptFormats.stampPrefix) { return nil }
            return ComparableLine(key: isGeneratedBy(text) ? Array(generatedByPrefix.utf8) : bytes, line: line)
        }
    }

    private static func isSkippableHeaderText(_ bytes: [UInt8]) -> Bool {
        bytes.allSatisfy { (0x20...0x7E).contains($0) && $0 != UInt8(ascii: "}") }
    }

    /// `  Generated by <app> on <ISO 8601 time>.`, as the generator writes it.
    private static func isGeneratedBy(_ line: String) -> Bool {
        guard let rest = line.strippingAffixes(generatedByPrefix, "."),
            let stamp = rest.components(separatedBy: " on ").last
        else { return false }
        return ISO8601DateFormatter().date(from: stamp) != nil
    }

    /// Past this many lines left to diff (file and script together, after
    /// matching the ends), the differing middle is reported whole instead:
    /// a Myers diff costs about lines x edits, and a file padded with
    /// 200,000 junk lines once took two minutes. Scripts are a few hundred
    /// lines, so a real edit is always diffed.
    static let maximumDiffLines = 2_000

    /// The lines only the file has, and those only the regenerated script
    /// has. The matching start and end are set aside first; what's left is
    /// diffed with the standard library's `difference(from:)` (a Myers
    /// diff, like `diff`/`git diff`), or reported whole if it's huge.
    private static func differences(
        _ file: [ComparableLine], _ generated: [ComparableLine]
    ) -> (fileOnly: [ReadScript.Line], generatedOnly: [String]) {
        let shorter = min(file.count, generated.count)
        var prefix = 0
        while prefix < shorter && file[prefix].key == generated[prefix].key { prefix += 1 }
        var suffix = 0
        while suffix < shorter - prefix && file[file.count - 1 - suffix].key == generated[generated.count - 1 - suffix].key {
            suffix += 1
        }
        let fileMiddle = Array(file[prefix..<(file.count - suffix)])
        let generatedMiddle = Array(generated[prefix..<(generated.count - suffix)])

        // One side empty is a pure insertion or deletion: nothing to diff.
        guard !fileMiddle.isEmpty, !generatedMiddle.isEmpty,
            fileMiddle.count + generatedMiddle.count <= maximumDiffLines
        else {
            return (fileMiddle.map(\.line), generatedMiddle.map(\.line.text))
        }
        // `\.key` is a key path -- a reference to a property, usable as a
        // function here, like `|line| line.key` in Rust.
        var fileOnly: [ReadScript.Line] = []
        var generatedOnly: [String] = []
        for change in fileMiddle.map(\.key).difference(from: generatedMiddle.map(\.key)) {
            switch change {
            case .insert(let offset, _, _): fileOnly.append(fileMiddle[offset].line)
            case .remove(let offset, _, _): generatedOnly.append(generatedMiddle[offset].line.text)
            }
        }
        return (fileOnly.sorted { $0.number < $1.number }, generatedOnly)
    }

    /// The labels `RandomSampleScriptGenerator` starts rule summary lines with.
    private static let ruleSummaryLabels = [
        "Rating filter:", "Category filter:", "Path filter:", "Keyword path filter:", "Keyword count filter:",
        "Label filter:", "File type filter:", "Bookmark filter:", "Pending deletion:",
        "Match all of:", "Match any of:", "Match none of:",
    ]

    private static func isRuleSummary(_ line: String) -> Bool {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        return ruleSummaryLabels.contains { trimmed.hasPrefix($0) }
    }
}
